name: uchat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  firebase_storage: ^12.2.0
  cloud_firestore: ^5.4.0
  provider: ^6.1.2
  image_picker: ^1.1.2
  fluttertoast: ^8.2.8
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  remove_alpha_ios: true  # Removes the alpha channel for iOS icons
  min_sdk_android: 21

  web:
    generate: true
    image_path: "assets/app_logo.png"
    background_color: "#FFFFFF"  # Replace with your background color
    theme_color: "#FFFFFF"  # Replace with your theme color

  windows:
    generate: true
    image_path: "assets/app_logo.png"
    icon_size: 48

  macos:
    generate: true
    image_path: "assets/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/app_logo.png  # Include only the app_logo.png
