// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcZXXgcjSbqXoVsc3snx_lVSiRKVfqNZs',
    appId: '1:908946012270:web:631cdff87709b4c4a4ce7f',
    messagingSenderId: '908946012270',
    projectId: 'uchat-6ea75',
    authDomain: 'uchat-6ea75.firebaseapp.com',
    storageBucket: 'uchat-6ea75.appspot.com',
    measurementId: 'G-3W5GCB1F72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLNNuRsXOouy2GblSF3U4sTgM-NSuRAM0',
    appId: '1:908946012270:android:4c3693c252623c92a4ce7f',
    messagingSenderId: '908946012270',
    projectId: 'uchat-6ea75',
    storageBucket: 'uchat-6ea75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7mJotJCbLPeKEPISdVvPE9Gv6t2FvwLo',
    appId: '1:908946012270:ios:8b6c6b8244c8900ca4ce7f',
    messagingSenderId: '908946012270',
    projectId: 'uchat-6ea75',
    storageBucket: 'uchat-6ea75.appspot.com',
    iosBundleId: 'com.example.uchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7mJotJCbLPeKEPISdVvPE9Gv6t2FvwLo',
    appId: '1:908946012270:ios:8b6c6b8244c8900ca4ce7f',
    messagingSenderId: '908946012270',
    projectId: 'uchat-6ea75',
    storageBucket: 'uchat-6ea75.appspot.com',
    iosBundleId: 'com.example.uchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcZXXgcjSbqXoVsc3snx_lVSiRKVfqNZs',
    appId: '1:908946012270:web:6fdce1028237a125a4ce7f',
    messagingSenderId: '908946012270',
    projectId: 'uchat-6ea75',
    authDomain: 'uchat-6ea75.firebaseapp.com',
    storageBucket: 'uchat-6ea75.appspot.com',
    measurementId: 'G-D4CQN3G9D4',
  );
}
